### PR TITLE
Remove removal of unused variable calls and replace them by a tslint exception

### LINKED ISSUE #68: Check all the code!
SIG needs to be happy at the end of the week

### PR DESCRIPTION
**Pull request by Exclaminator**
Will close #68.

This removes function calls that were only used to suppress TSlint and replaces them with temporarily disabling checking for unused variables and then re-enabling checking for unused variables.

### CODE REVIEW

File: src/octopeer-github/main/Database/ConstantDatabasePoster.ts [hunk 1]
```diff
@@ -78,3 +78,4 @@ function constantDatabasePoster() {
         }));
     }
 }
+/* tslint:enable:no-unused-variable */
```
Comment (mpsijm) [inline src/octopeer-github/main/Database/ConstantDatabasePoster.ts]: You don't need to re-enable tslint here, because of `disable-next-line`.

File: src/octopeer-github/main/Logger.ts [hunk 2]
```diff
@@ -6,6 +6,7 @@
  * The Logger class (singleton) is used to log events to the console.
  * The Logger will not output debug messages if this is not explicitly requested.
  */
+/* tslint:disable:no-unused-variable */
```
Comment (mpsijm) [inline src/octopeer-github/main/Logger.ts]: Please also use `disable-next-line` here.

File: src/octopeer-github/main/Database/DatabaseAdaptable.ts [hunk 3]
```diff
@@ -29,3 +29,4 @@ type UnixTimestamp = number;
  */
 interface DatabaseAdaptable extends SemanticDatabaseAdaptable, KeystrokeDatabaseAdaptable, MousePositionDatabaseAdaptable,
     MouseClickDatabaseAdaptable, MouseScrollDatabaseAdaptable, WindowResolutionDatabaseAdaptable { }
+
```
Comment (mpsijm) [inline src/octopeer-github/main/Database/DatabaseAdaptable.ts]: Can you remove the superfluous new-line at the end of this file?

**Comment by mpsijm** [comment]
We don't look at coverage for this PR, since no actual source code has been changed. Approved for merging! :)

**Comment by mdingjan** [comment]
Can you enable the tslint warning at the end of the adapted files as well?
Just a (good) convention :)

**Comment by Exclaminator** [comment]
@mdingjan where would you like me to add this, all the TSlint exemptions are for the next line only.

**Comment by mdingjan** [comment]
Will merge!
